Repository animator/learn-python, pull requests merged in 2024-06, with the labels that each got.

#817 Updated index.md and added exception-handling.md under the issue #640
  contrib/advanced-python/exception-handling.md
  contrib/advanced-python/index.md
Labels: gssoc, level2

#720 Added Clustering
  contrib/machine-learning/clustering.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#711 [#526] CNN From Scratch
  contrib/machine-learning/assets/cnn-dropout.png
  contrib/machine-learning/assets/cnn-filters.png
  contrib/machine-learning/assets/cnn-flattened.png
  contrib/machine-learning/assets/cnn-input_shape.png
  contrib/machine-learning/assets/cnn-ouputs.png
  contrib/machine-learning/assets/cnn-padding.png
  contrib/machine-learning/assets/cnn-pooling.png
  contrib/machine-learning/assets/cnn-strides.png
  contrib/machine-learning/index.md
  contrib/machine-learning/intro-to-cnn.md
Labels: gssoc, level2

#652 Added Random Forest
  contrib/machine-learning/index.md
  contrib/machine-learning/random-forest.md
Labels: gssoc, level2

#724 created Sliding_Window.md and updated index.md
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/sliding-window.md
Labels: gssoc, level2

#725 Trie Data Structure in Python
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/trie.md
Labels: gssoc, level2

#727 Introducing Matplotlib
  contrib/plotting-visualization/images/barplot.png
  contrib/plotting-visualization/images/histogram.png
  contrib/plotting-visualization/images/scatterplot.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/matplotlib-introduction.md
Labels: gssoc, level2

#660 Added viewing_data_in_pandas.md file
  contrib/pandas/index.md
  contrib/pandas/viewing-data.md
Labels: gssoc, level1

#734 Added Content: Line Charts in Matplotlib
  contrib/plotting-visualization/images/dot-line.png
  contrib/plotting-visualization/images/line-asymptote.png
  contrib/plotting-visualization/images/line-curve.png
  contrib/plotting-visualization/images/line-labels.png
  contrib/plotting-visualization/images/line-ticks.png
  contrib/plotting-visualization/images/line-with-text-scale.png
  contrib/plotting-visualization/images/simple_line.png
  contrib/plotting-visualization/images/two-lines.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/matplotlib-line-plot.md
Labels: gssoc, level2

#721 Added sklearn.md file
  contrib/machine-learning/index.md
  contrib/machine-learning/sklearn-introduction.md
Labels: gssoc, level2

#766 Added content for seaborn
  contrib/plotting-visualization/images/seaborn-basics1.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/seaborn-basics.md
  contrib/plotting-visualization/seaborn-intro.md
Labels: gssoc, level2

#726 Added types of cost functions
  contrib/machine-learning/cost-functions.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#693 Updated index.md and added stacks.md under the issue #349
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/stacks.md
Labels: gssoc, level2

#779 Content Added: Protocols
  contrib/advanced-python/index.md
  contrib/advanced-python/protocols.md
Labels: gssoc, level2

#838 Added Generators under Advance python
  contrib/advanced-python/generators.md
  contrib/advanced-python/index.md
Labels: gssoc, level2

#825 Added Hierarchical Clustering
  contrib/machine-learning/hierarchical-clustering.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#968 Added K-Nearest Neighbors (KNN).md file
  contrib/machine-learning/index.md
  contrib/machine-learning/knn.md
Labels: gssoc, level2

#826 Added Ensemble Learning in machine learning
  contrib/machine-learning/ensemble-learning.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#832 GSSoC'24: Add a guide on Transformers
  contrib/machine-learning/assets/transformer-architecture.png
  contrib/machine-learning/index.md
  contrib/machine-learning/transformers.md
Labels: gssoc, level2

#872 eval function
  contrib/advanced-python/eval_function.md
  contrib/advanced-python/index.md
Labels: gssoc, level1

#891 Added Content on List Comprehension under Advanced Python Module
  contrib/advanced-python/index.md
  contrib/advanced-python/list-comprehension.md
Labels: gssoc, level2

#969 Added Content: Scatter Plot in Matplotlib
  contrib/plotting-visualization/images/img_colorbar.png
  contrib/plotting-visualization/images/scatter_color.png
  contrib/plotting-visualization/images/scatter_coloreachdot.png
  contrib/plotting-visualization/images/scatter_colormap1.png
  contrib/plotting-visualization/images/scatter_colormap2.png
  contrib/plotting-visualization/images/scatter_compare.png
  contrib/plotting-visualization/images/simple_scatter.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/matplotlib-scatter-plot.md
Labels: gssoc, level2

#974 Added Content: Hashing through Linear Probing
  contrib/ds-algorithms/hashing-linear-probing.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#980 Rename Queues.md to queues.md
  contrib/ds-algorithms/queues.md
Labels: gssoc

#1015 Create Type_Hinting.md
  contrib/advanced-python/type-hinting.md
Labels: gssoc, level2

#1017 Create Itertools_module.md
  contrib/advanced-python/itertools.md
Labels: gssoc, level2

#1004 Added two-pointer-technique.md and updated index.md
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/two-pointer-technique.md
Labels: gssoc, level2

#975 Added Content: Hashing through Chaining
  contrib/ds-algorithms/hashing-chaining.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level1

#1003 Added Filter and Reduce Functions
  contrib/advanced-python/filter-function.md
  contrib/advanced-python/index.md
  contrib/advanced-python/reduce-function.md
Labels: gssoc, level2

#1011 Update sorting-algorithms.md
  contrib/ds-algorithms/sorting-algorithms.md
Labels: gssoc, level2

#1019 Added Closures for Advanced Python
  contrib/advanced-python/closures.md
  contrib/advanced-python/index.md
Labels: gssoc, level2

#1007 Match case statements
  contrib/advanced-python/index.md
  contrib/advanced-python/match-case.md
Labels: gssoc, level2

#1070 Added Splay Trees in DSA section
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/splay-trees.md
Labels: gssoc, level2

#1089 Added AVL Trees in DSA section
  contrib/ds-algorithms/avl-trees.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#1093 Added the Universal Functions file under NumPy directory
  contrib/numpy/index.md
  contrib/numpy/universal-functions.md
Labels: gssoc, level2

#1111 Added Content on Magic Methods under Advanced Python Module
  contrib/advanced-python/index.md
  contrib/advanced-python/magic-methods.md
Labels: gssoc, level2

#1074 Added hash-tables, sets, and maps
  contrib/ds-algorithms/hash-tables.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#1095 Added Binary tree
  contrib/ds-algorithms/binary-tree.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#1105 Added Neural Network Regression ML Algorithm in Python
  contrib/machine-learning/index.md
  contrib/machine-learning/neural-network-regression.md
Labels: gssoc, level2

#1110 Added content on naive bayes
  contrib/machine-learning/index.md
  contrib/machine-learning/naive-bayes.md
Labels: gssoc, level2

#1112 SciPy Graphs
  contrib/scipy/index.md
  contrib/scipy/scipy-graphs.md
Labels: gssoc, level2

#1117 Added Heaps Data Structure
  contrib/ds-algorithms/heaps.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#1118 Added Polynomial Regression
  contrib/machine-learning/index.md
  contrib/machine-learning/polynomial-regression.md
Labels: gssoc, level2

#1124 Statistical operations numpy
  contrib/numpy/index.md
  contrib/numpy/statistical-functions.md
Labels: gssoc, level2

#1125 Splitting arrays numpy
  contrib/numpy/index.md
  contrib/numpy/splitting-arrays.md
Labels: gssoc, level1

#1137 Added Content for Asynchronous Context managers and generators
  contrib/advanced-python/asynchronous-context-managers-generators.md
  contrib/advanced-python/index.md
Labels: gssoc, level2

#1157 Content Added: "PyTorch Fundamentals"
  contrib/machine-learning/index.md
  contrib/machine-learning/pytorch-fundamentals.md
Labels: gssoc, level2

#1235 Introduction to Bar Plots in Plotly
  contrib/plotting-visualization/images/plotly-bar-colors-basic.png
  contrib/plotting-visualization/images/plotly-bar-colors.png
  contrib/plotting-visualization/images/plotly-bar-labels-1.png
  contrib/plotting-visualization/images/plotly-bar-labels-2.png
  contrib/plotting-visualization/images/plotly-bar-labels-3.png
  contrib/plotting-visualization/images/plotly-bar-title.png
  contrib/plotting-visualization/images/plotly-basic-bar-plot.png
  contrib/plotting-visualization/images/plotly-horizontal-bar-plot.png
  contrib/plotting-visualization/images/plotly-long-format-bar-plot.png
  contrib/plotting-visualization/images/plotly-rounded-bars.png
  contrib/plotting-visualization/images/plotly-wide-format-bar-plot.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/plotly-bar-plots.md
Labels: gssoc, level2

#593 Added SeabornPlotting Functions #480
  contrib/plotting-visualization/images/seaborn-plotting/image1.png
  contrib/plotting-visualization/images/seaborn-plotting/image10.png
  contrib/plotting-visualization/images/seaborn-plotting/image11.png
  contrib/plotting-visualization/images/seaborn-plotting/image12.png
  contrib/plotting-visualization/images/seaborn-plotting/image13.png
  contrib/plotting-visualization/images/seaborn-plotting/image14.png
  contrib/plotting-visualization/images/seaborn-plotting/image15.png
  contrib/plotting-visualization/images/seaborn-plotting/image16.png
  contrib/plotting-visualization/images/seaborn-plotting/image2.png
  contrib/plotting-visualization/images/seaborn-plotting/image3.png
  contrib/plotting-visualization/images/seaborn-plotting/image4.png
  contrib/plotting-visualization/images/seaborn-plotting/image5.png
  contrib/plotting-visualization/images/seaborn-plotting/image6.png
  contrib/plotting-visualization/images/seaborn-plotting/image7.png
  contrib/plotting-visualization/images/seaborn-plotting/image8.png
  contrib/plotting-visualization/images/seaborn-plotting/image9.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/seaborn-plotting.md
Labels: gssoc, level2

#1259 Updated Threading,md (Added threading module in Advanced Python Module)
  contrib/advanced-python/index.md
  contrib/advanced-python/threading.md
Labels: gssoc, level2

#1261 XGBoost Topic
  contrib/machine-learning/assets/XG_1.webp
  contrib/machine-learning/index.md
  contrib/machine-learning/xgboost.md
Labels: gssoc, level2

#1256 Update index.md
  contrib/machine-learning/index.md
Labels: gssoc

#1100 Pandas Series
  contrib/pandas/index.md
  contrib/pandas/pandas-series.md
Labels: gssoc, level2

#1096 Reinforcement Learning
  contrib/machine-learning/index.md
  contrib/machine-learning/reinforcement-learning.md
Labels: gssoc, level2

#1284 Added Cyclic Sort algorithm
  contrib/ds-algorithms/sorting-algorithms.md
Labels: gssoc, level1
