Repository animator/learn-python, pull requests merged in 2024-05, with the labels that each got.

#92 added API methods to the documentation
  contrib/api-development/api-methods.md
  contrib/api-development/index.md
Labels: gssoc, level2

#134 First version of python was 0.9.0
  README.md
Labels: gssoc, level1

#192 Updated index.md and added sorting-algorithms.md under issue #191
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/sorting-algorithms.md
Labels: gssoc, level3

#488 Create regular_expressions.md
  contrib/advanced-python/regular_expressions.md
Labels: gssoc, level2

#484 Create dates_and_times.md
  contrib/advanced-python/dates_and_times.md
Labels: gssoc, level2

#215 Added a mini project
  contrib/mini-projects/dice_roller.md
  contrib/mini-projects/index.md
Labels: gssoc, level2

#291 Added Mini Project - Rock Paper Scissors game
  contrib/mini-projects/Rock_Paper_Scissors_Game.md
  contrib/mini-projects/index.md
Labels: gssoc, level2

#353 Added Regression in Machine Learning
  contrib/machine-learning/Regression.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#351 Added Excel using Pandas DataFrame section under Pandas Module
  contrib/pandas/excel_with_pandas.md
  contrib/pandas/index.md
Labels: gssoc, level2

#350 Added Path Finder mini project
  contrib/mini-projects/index.md
  contrib/mini-projects/path-finder.md
Labels: gssoc, level2

#348 Added content: Confusion Matrix and SVM
  contrib/machine-learning/confusion-matrix.md
  contrib/machine-learning/index.md
  contrib/machine-learning/support-vector-machine.md
Labels: gssoc, level3

#370 Modified Content
  contrib/machine-learning/ArtificialNeuralNetwork.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#371 [Add content] advance python: JSON module
  contrib/advanced-python/index.md
  contrib/advanced-python/json-module.md
Labels: gssoc, level2

#388 Descriptive Statistics with Python and Pandas
  contrib/pandas/Descriptive_Statistics.md
  contrib/pandas/index.md
Labels: gssoc, level3

#395 Added OOPs
  contrib/advanced-python/OOPs.md
  contrib/advanced-python/index.md
Labels: gssoc, level2

#402 Closes #294 - Mini Project : Password Strength Checker
  contrib/mini-projects/index.md
  contrib/mini-projects/password_strength_checker.md
Labels: gssoc, level2

#398 Created Hangman game with reference to assigned issue #185
  contrib/mini-projects/hangman_game.md
  contrib/mini-projects/index.md
Labels: gssoc, level2

#399 Recursion and Backtracking
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/recursion.md
Labels: gssoc, level2

#409 Added TensorFlow,md File
  contrib/machine-learning/index.md
  contrib/machine-learning/tensorFlow.md
Labels: gssoc, level1

#448 GroupBy_Pandas
  contrib/pandas/GroupBy_Functions_Pandas.md
  contrib/pandas/index.md
Labels: gssoc, level2

#463 Installing numpy
  contrib/numpy/index.md
  contrib/numpy/installing-numpy.md
Labels: gssoc, level1

#499 "Added Content Decision Trees"
  contrib/machine-learning/Decision-Tree.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#483 Updated ds-algorithm
  contrib/ds-algorithms/divide-and-conquer-algorithm.md
  contrib/ds-algorithms/dynamic-programming.md
  contrib/ds-algorithms/greedy-algorithms.md
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/searching-algorithms.md
Labels: gssoc, level3

#482 Updated index.md and added Queues.md under issue #176
  contrib/ds-algorithms/Queues.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#471 Added Content: Numpy datatypes
  contrib/numpy/datatypes.md
  contrib/numpy/index.md
Labels: gssoc, level2

#464 Operation on numpy
  contrib/numpy/index.md
  contrib/numpy/operations-on-arrays.md
Labels: gssoc, level2

#465 Binomial Distribution using Python
  contrib/machine-learning/binomial_distribution.md
  contrib/machine-learning/index.md
Labels: gssoc, level2

#449 Added Loading Arrays from Files section under NumPy module
  contrib/numpy/index.md
  contrib/numpy/loading_arrays_from_files.md
Labels: gssoc, level2

#406 Adding content to Basic Mathematics in Python
  contrib/numpy/basic_math.md
  contrib/numpy/index.md
Labels: gssoc, level2

#309 Create TIC_TAC_TOE_GAME.md
  contrib/mini-projects/index.md
  contrib/mini-projects/tic-tac-toe.md
Labels: gssoc, level2

#427 Added graph.md file
  contrib/ds-algorithms/graph.md
  contrib/ds-algorithms/index.md
Labels: gssoc, level2

#507 Installation of Scipy and its key uses
  contrib/scipy/index.md
  contrib/scipy/installation_features.md
Labels: gssoc, level2

#536 Added Saving Arrays into Files section under NumPy module
  contrib/numpy/index.md
  contrib/numpy/saving_numpy_arrays_to_files.md
Labels: gssoc, level2

#549 Add content: Pandas introduction and DataFrames
  contrib/pandas/index.md
  contrib/pandas/introduction.md
Labels: gssoc, level2

#553 create lambda-function.md
  contrib/advanced-python/index.md
  contrib/advanced-python/lambda-function.md
Labels: gssoc, level2

#568 Added Introduction to MySQL Queries
  contrib/database/index.md
  contrib/database/intro_mysql_queries.md
Labels: gssoc, level2

#594 Add Content: Importing and Exporting Data in Pandas
  contrib/pandas/Datasets/car-sales.csv
  contrib/pandas/Datasets/readme.md
  contrib/pandas/import-export.md
  contrib/pandas/index.md
Labels: gssoc, level2

#618 FastAPI tutorial completed. Closes [#456]
  contrib/api-development/assets/image.png
  contrib/api-development/assets/image2.png
  contrib/api-development/fast-api.md
  contrib/api-development/index.md
Labels: gssoc, level3

#570 create map-function.md
  contrib/advanced-python/index.md
  contrib/advanced-python/map-function.md
Labels: gssoc, level1

#584 Updated sorting-algorithms.md
  contrib/ds-algorithms/sorting-algorithms.md
Labels: gssoc, level2

#627 Added Working with datetime using Pandas section under Pandas Module
  contrib/pandas/datetime.md
  contrib/pandas/index.md
Labels: gssoc, level2

#641 [Add Content] - Data Structure & Algorithms - Add about Time and Space Complexity
  contrib/ds-algorithms/images/Time-And-Space-Complexity-BigOh.png
  contrib/ds-algorithms/images/Time-And-Space-Complexity-BigOmega.png
  contrib/ds-algorithms/images/Time-And-Space-Complexity-BigTheta.png
  contrib/ds-algorithms/index.md
  contrib/ds-algorithms/time-space-complexity.md
Labels: gssoc, level2

#657 Added Content: Bar Plots in Matplotlib
  contrib/plotting-visualization/bar-plots.md
  contrib/plotting-visualization/images/bar_colors_and_legends.png
  contrib/plotting-visualization/images/bar_labels.png
  contrib/plotting-visualization/images/basic_bar_plot.png
  contrib/plotting-visualization/images/horizontal_bar_plot_1.png
  contrib/plotting-visualization/images/horizontal_bar_plot_2.png
  contrib/plotting-visualization/images/title_and_axis_labels.png
  contrib/plotting-visualization/index.md
Labels: gssoc, level2

#674 Added Content on NumPy Array Iteration under NumPy module
  contrib/numpy/array-iteration.md
  contrib/numpy/index.md
Labels: gssoc, level2

#677 Added Logistic Regression
  contrib/machine-learning/index.md
  contrib/machine-learning/logistic-regression.md
Labels: gssoc, level2

#698 Numpy array reshape
  contrib/numpy/index.md
  contrib/numpy/reshape-array.md
Labels: gssoc, level2

#712 Added Content: Pie Charts in Matplotlib
  contrib/plotting-visualization/images/autopct.png
  contrib/plotting-visualization/images/basic_pie_chart.png
  contrib/plotting-visualization/images/coloring_slices.png
  contrib/plotting-visualization/images/explode_slice.png
  contrib/plotting-visualization/images/hatch_patterns.png
  contrib/plotting-visualization/images/legends.png
  contrib/plotting-visualization/images/radius.png
  contrib/plotting-visualization/images/rotating_slices.png
  contrib/plotting-visualization/images/shadow.png
  contrib/plotting-visualization/index.md
  contrib/plotting-visualization/matplotlib-pie-charts.md
Labels: gssoc, level2

#714 Added content on Grid Search
  contrib/machine-learning/grid-search.md
  contrib/machine-learning/index.md
Labels: gssoc, level2
